### ISSUE TITLE
Add Table of Contents in the README.md file

### ISSUE THREAD

**Issue by Maryam0330** [nishant4500/object-detection#2] opened 2024-10-12 15:42 UTC
I would like to add a Table of Contents section to the README file to enhance navigation and provide a more user-friendly experience for end users. This will enable quick access to key sections and improve the overall readability of the project.

Please assign me this task under `hacktoberfest` and `gssoc-ext` label

**Comment by nishant4500** [comment] 2024-10-12 16:48
go for it 
make sure you mark star for it 

Some Important points to mention:


Issues are assigned based on first come first server.
Any change related to the design of the website needs a design proposal or reference first.
Please raise Prs only if the issue is assigned to you.
Please start working on the issue only after it is assigned to you.
Rest you can add more if you have any points in mind.

**Comment by Maryam0330** [comment] 2024-10-13 05:54
@nishant4500 I have added the `Table of Contents` section under #2 issue. Please merge it.

**Closed as completed** 2024-10-13 06:20 UTC
Labels: gssoc-ext, hacktoberfest, level 1
